language: PYTHON
sudo: required
warnings_are_errors: true
install:
    - pip install -r requirements.txt
    - pip install coveralls
script: 
    - python manage.py migrate 
    - coverage run --source=portal manage.py test
after_success:
    coveralls
